import { Info } from "lucide-react";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";

export const DisclaimerBanner = () => {
  return (
    <Alert variant="default" className="bg-blue-50 dark:bg-blue-950 border-blue-200 dark:border-blue-900 mb-6">
      <Info className="h-4 w-4 text-blue-600 dark:text-blue-400" />
      <AlertTitle className="text-blue-800 dark:text-blue-300">AI Generated Content</AlertTitle>
      <AlertDescription className="text-blue-700 dark:text-blue-400">
        This travel plan was generated by AI and may contain inaccuracies. Please verify opening hours, prices, and
        availability before booking.
      </AlertDescription>
    </Alert>
  );
};
