import type { GeneratedPlanDto } from "../../types";

export class MockAIService {
  async complete(): Promise<GeneratedPlanDto> {
    // Simulate network delay to mimic real API behavior
    await new Promise((resolve) => setTimeout(resolve, 800));

    return {
      destination_name: "Mock Destination: Kyoto, Japan",
      plan_data: {
        introduction: "This is a MOCKED response generated for testing purposes because MOCK_AI_RESPONSE is set to true. Kyoto is famous for its classical Buddhist temples, as well as gardens, imperial palaces, Shinto shrines and traditional wooden houses.",
        why_visit: "You should visit to verify that the frontend correctly renders this mocked data without hitting the real AI API. It's a safe environment for e2e tests.",
        things_to_do: "- Verify the plan header\n- Check the 'Save' button functionality\n- Check the 'Discard' button functionality\n- Verify the disclaimer text",
        sample_itinerary: "Day 1: Arrive in Mock City. \nDay 2: Run automated tests. \nDay 3: Validate UI components."
      },
      disclaimer: "DISCLAIMER: This content is a MOCK response for development and testing. It was not generated by AI."
    };
  }
}

export const mockAiService = new MockAIService();
